// Write down the schema the migrations describe, for the Worker to read.
//
// The column checker compares the hand-written lists against the migration
// files, which answers "is the code consistent with the migrations" and not
// "is the database consistent with the migrations". Those came apart:
// 0016_reminders.sql was never applied to production, so every payments query
// selected p.reminded_at from a table that did not have it, and the Payments
// page returned a 500 for weeks. Nothing offline could have caught it, because
// offline there is no database to be wrong.
//
// So the expected schema is written into a file the Worker ships with, and
// /api/admin/health compares it to what D1 actually holds. Generated rather
// than hand-kept: a list of columns maintained by hand is the exact failure
// this whole family of checks exists to stop.
//
//   node scripts/gen-schema.mjs        rewrite the file
//
// check-columns.mjs fails if the file is stale, so a migration added without
// regenerating does not reach main.

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { schemaFromMigrations } from './lib/schema.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
export const TARGET = join(ROOT, 'src', 'schema-expected.js');

export function render(root = ROOT) {
  const origins = new Map();
  const tables = [...schemaFromMigrations(root, { origins })].sort(([a], [b]) => a.localeCompare(b));
  const body = tables
    .map(([table, cols]) => `  ${table}: [${[...cols].sort().map((c) => `'${c}'`).join(', ')}],`)
    .join('\n');

  // Which migration introduces each column, so a column the database is
  // missing can name the file that would add it rather than leaving somebody
  // to grep the migrations for it.
  const origin = [...origins].sort(([a], [b]) => a.localeCompare(b))
    .map(([key, file]) => `  '${key}': '${file}',`).join('\n');

  return `// Generated by scripts/gen-schema.mjs. Do not edit by hand.
//
// The schema as the migrations leave it: what the database should hold if
// every migration has been applied. Compared against the live database by
// schemaDrift() in src/schema-drift.js, reported on /api/admin/health.

export const EXPECTED_SCHEMA = {
${body}
};

/** "table.column" -> the migration file that adds it. */
export const COLUMN_ORIGIN = {
${origin}
};
`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  writeFileSync(TARGET, render());
  console.log(`wrote ${TARGET}`);
}
